export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const FETCH_INGREDIENT = 'FETCH_INGREDIENT';
export const SET_INGREDIENT = 'SET_INGREDIENT';
export const FETCH_INGREDINT_FAILED = 'FETCH_INGREDIENT_FAILED';

